- alias: Turn on away from Telegram
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/AWAY_ON'
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: input_boolean.away

- alias: Turn off away from Telegram
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/AWAY_OFF'
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.away