title: Home Assistant

resources:
  - url: /local/community/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/community/button-entity-row/button-entity-row.js
    type: module
  - url: /local/community/weather-card/weather-card.js
    type: module
  - url: /local/community/custom-header/custom-header.js
    type: module
  - url: /local/community/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /local/community/upcoming-media-card/upcoming-media-card.js
    type: module
  - url: /local/community/travel-time-card/travel-time-card.js
    type: module
  - url: /local/community/atomic_calendar/atomic_calendar.js
    type: module

custom_header:
  compact_mode: true
 
views: !include_dir_list ui/
