title: Home Assistant

resources:
  - url: /local/custom_components/mini-media-player/mini-media-player.bundle.js?v=1.6.0
    type: module
  - url: /local/custom_components/travel-time/travel-time.bundle.js
    type: js
  - url: /local/custom_components/calendar/calendar-card.js
    type: module
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
    
views:
  - !include ui/home.yaml
  - !include ui/livingroom.yaml
  - !include ui/bedroom.yaml
  - !include ui/settings.yaml