title: Home Assistant

resources:
  - url: /local/community/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/community/button-entity-row/button-entity-row.js
    type: module
    
views: !include_dir_list ui/
