- platform: group
  name: Lichten woonkamer
  entities:
    - light.woonkamer

- platform: group
  name: Lichten badkamer
  entities:
    - light.badkamer
    - light.badkamer_spiegel_links

- platform: group
  name: Lichten keuken
  entities:
    - light.keuken_links
    - light.keuken_rechts
  
- platform: group
  name: Lichten gang
  entities:
    - light.gang

- platform: group
  name: Lichten slaapkamer
  entities:
    - light.slaapkamer_2

- platform: group
  name: Lichten eettafel
  entities:
    - light.eettafel_links
    - light.eettafel_rechts

- platform: group
  name: Lichten
  entities:
    - light.lichten_badkamer
    - light.lichten_eettafel
    - light.lichten_gang
    - light.lichten_keuken
    - light.lichten_slaapkamer
    - light.lichten_woonkamer

- platform: philips_ambilight
  name: TV Ambilight
  host: 192.168.2.2
  username: !secret philips_tv_username
  password: !secret philips_tv_password
