- name: Travel time to work
  platform: waze_travel_time
  origin: device_tracker.pascal_htcu12
  destination: !secret waze_work_destination
  region: 'EU'

- name: Travel time to home
  platform: waze_travel_time
  origin: device_tracker.pascal_htcu12
  destination: !secret waze_home_destination
  region: 'EU'

- platform: travisci
  api_key: !secret github_api_key
  repository:
    - ha-config
    
- platform: trakt
  id: !secret trakt_client_id
  secret: !secret trakt_client_secret
  username: pascalwilbrink
  days: 10

- platform: p2000
  regios: 4
  radius: 20000
  scan_interval: 30


- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'