- name: Travel time to work
  platform: waze_travel_time
  origin: device_tracker.pascal_htcu12
  destination: !secret waze_work_destination
  region: 'EU'

- name: Travel time to home
  platform: waze_travel_time
  origin: device_tracker.pascal_htcu12
  destination: !secret waze_home_destination
  region: 'EU'

- platform: travisci
  api_key: !secret github_api_key