- platform: template
  sensors:
    presence:
      device_class: presence
      friendly_name: "Presence"
      value_template: >-
        {%- if is_state('input_boolean.automatic_presence', 'on') and is_state('device_tracker.pascal_htcu12', 'home') -%}
          on
        {%- elif is_state('input_boolean.automatic_presence', 'off') and is_state('input_boolean.presence', 'on') -%}
          on
        {%- elif is_state('input_boolean.automatic_presence', 'off') and is_state('input_boolean.presence', 'off') -%}
          off
        {%- else -%}
          off
        {%- endif -%}