- platform: template
  sensors:
    presence:
      device_class: occupancy
      friendly_name: "Home occupied"
      entity_id:
       - input_boolean.automatic_presence
       - input_boolean.presence
       - device_tracker.pascal_htcu12
      value_template: >-
        {{    
            (is_state('input_boolean.automatic_presence', 'on') and is_state('device_tracker.pascal_htcu12', 'home'))
          or 
            (is_state('input_boolean.automatic_presence', 'off') and is_state('input_boolean.presence', 'on'))
        }}