- alias: 'Send Telegram message when leaving and automatic presence detection is off'
  trigger:
    - platform: state
      entity_id: device_tracker.htc_u12
      from: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_presence
      state: 'off'
  action:
    service: telegram_bot.send_message
    data:
      message: 'Aanwezigheidsdetectie is uitgeschakeld. Inschakelen?'
      target: !secret telegram_chat_id
      inline_keyboard: 
        - 'Aanzetten:/AUTOMATIC_PRESENCE_ON'
        - 'Uitgeschakeld laten:/AUTOMATIC_PRESENCE_OFF'

- alias: 'Turn on automatic presence detection'
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: '/AUTOMATIC_PRESENCE_ON'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_presence
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.automatic_presence
    - service: telegram_bot.delete_message
      data:
        chat_id: !secret telegram_chat_id
        message_id: trigger.event.data.message.message_id

- alias: 'Turn off all the lights when presence is off'
  trigger:
    - platform: state
      entity_id: binary_sensor.presence
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.lichten

- alias: 'Living Room occupied'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: "{{ not is_state('media_player.android_tv', 'unavailable') }}"
    - platform: template
      value_template: "{{ not is_state('media_player.living_room', 'playing') }}"
    - platform: template
      value_template: "{{ not is_state('media_player.android_tv', 'off') }}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.living_room_occupied

- alias: 'Wekker'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.wake_up_alarm
      to: 'on'
  action:
    - service: persistent_notification.create
      data:
        message: "Your message goes here"
        title: "Custom subject"