alias: 'Send Telegram message when leaving and automatic presence detection is off'
trigger:
  - platform: state
    entity_id: device_tracker.htc_u12
    from: 'home'
condition:
  - condition: state
    entity_id: input_boolean.automatic_presence
    state: 'off'
action:
  service: telegram_bot.send_message
  data:
    message: 'Aanwezigheidsdetectie is uitgeschakeld. Inschakelen?'
    target: !secret telegram_chat_id
    inline_keyboard: 
      - 'Aanzetten:/AUTOMATIC_PRESENCE_ON'
      - 'Uitgeschakeld laten:/AUTOMATIC_PRESENCE_OFF'
