alias: 'Turn off kitchen occupied when no motion'

trigger:
  - platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'off'

condition:
  - condition: state
    entity_id: input_boolean.kitchen_occupied
    state: 'on'

action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.kitchen_occupied
