alias: 'Turn off Bathroom occupied when door opened'

trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_door
    to: 'on'

condition:
  - condition: state
    entity_id: input_boolean.automatic_lights
    state: 'on'

  - condition: state
    entity_id: input_boolean.bathroom_occupied
    state: 'on'
    
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bathroom_occupied
