alias: 'Turn on automatic home occupancy detection'
trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/AUTOMATIC_HOME_OCCUPANCY_ON'
condition:
  - condition: state
    entity_id: input_boolean.automatic_home_occupancy
    state: 'off'
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.automatic_home_occupancy
  - service: telegram_bot.delete_message
    data:
      chat_id: !secret telegram_chat_id
      message_id: trigger.event.data.message.message_id