alias: 'Turn on Bedroom occupied when door opened'

trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_door
    to: 'on'

condition:
  - condition: state
    entity_id: input_boolean.bedroom_occupied
    state: 'off'
    
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.bedroom_occupied
