alias: 'Turn on livingroom light when tv turned off at night'

trigger:
  - platform: state
    entity_id: binary_sensor.home_occupancy
    to: 'off'

action:
  - service: light.turn_off
    data:
      entity_id: light.lichten