alias: 'Wekker'
trigger:
  - platform: state
    entity_id: binary_sensor.wake_up_alarm
    to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.lichten_slaapkamer
      brightness: 255
      kelvin: 2700
      transition: 300
  - service: spotcast.start
    data:
      uri: 'spotify:playlist:37i9dQZEVXcMWTflsxeSlz'
      transfer_playback: false
      entity_id: media_player.google_home_woonkamer