- alias: 'Wekker'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.wake_up_alarm
      to: 'on'
  action:
    - service: persistent_notification.create
      data:
        message: "Your message goes here"
        title: "Custom subject"
