alias: 'Werk wekker'

trigger:
  - platform: state
    entity_id: binary_sensor.wake_up_alarm
    to: 'on'

condition:
  - condition: state
    entity_id: binary_sensor.work_today
    state: 'on'

action:
  - service: light.turn_on
    data:
      entity_id: light.lichten_slaapkamer
      brightness: 255
      kelvin: 2700
      transition: 300

  - service: media_player.volume_set
    data:
      entity_id: media_player.slaapkamer
      volume_level: .35

  - service: spotcast.start
    data:
      uri: 'spotify:playlist:37i9dQZEVXcMWTflsxeSlz'
      transfer_playback: false
      entity_id: media_player.slaapkamer
