title: Settings
icon: mdi:settings
cards:
  - type: entities
    title: Occupances
    show_header_toggle: false
    entities:
      - entity: input_boolean.automatic_home_occupancy
        name: Automatic Home Occupancy Detection
        icon: mdi:home-map-marker
      - entity: input_boolean.automatic_livingroom_occupancy
        name: Automatic Livingroom Occupancy Detection
        icon: mdi:sofa
      - entity: input_boolean.automatic_bathroom_occupancy
        name: Automatic Bathroom Occupancy Detection
        icon: mdi:shower
      - entity: input_boolean.automatic_bedroom_occupancy
        name: Automatic Bedroom Occupancy Detection
        icon: mdi:bed-empty

  - type: entities
    title: Automations
    show_header_toggle: false
    entities:
      - entity: automation.turn_on_automatic_home_occupancy_detection
        name: '[Telegram callback]Turn on automatic home occupancy detection'
      - entity: automation.send_telegram_message_when_leaving_and_automatic_home_occupancy_detection_is_off
        name: send Telegram message when leaving and automatic home occupancy detection is off

  - type: entities
    title: Overrides
    show_header_toggle: false
    entities:
      - entity: input_boolean.override_home_occupancy
        name: Home occupancy
        icon: mdi:home-map-marker
      - entity: input_boolean.override_livingroom_occupancy
        name: Livingroom occupancy
        icon: mdi:sofa
      - entity: input_boolean.override_bedroom_occupancy
        name: Bedroom occupancy
        icon: mdi:bed-empty
      - entity: input_boolean.override_bathroom_occupancy
        name: Bathroom occupancy
        icon: mdi:shower
